
service: skellington

provider:
    name: aws
    runtime: nodejs8.10

functions:
    masquerade:
        handler: skellington.talk
        events:
            - http:
                path: talk
                method: POST
